---
title: "Assignment No.3"
author: "Elior Bliah"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    df_print: kable
    results: hide
    theme: flatly
    toc: yes
  word_document:
    toc: yes
---

# Preface

## Open Q1

## Open Q2


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r loading, warning=FALSE, include=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, magrittr, tidymodels, caret, DALEX, rpart, rattle, rpart.plot, RColorBrewer, ada, doParallel, pROC)
```

```{r}
cl <- makePSOCKcluster(5)
registerDoParallel(cl)
```

```{r load wine_data+split, include=FALSE}
urlfile= "https://raw.githubusercontent.com/ml4econ/problem-sets-2020/master/datasets/winequality_red.csv"
winequality_red<- read_csv(url(urlfile))
set.seed(167)
wine_split<- initial_split(winequality_red)
wine_train<- training(wine_split)
wine_test<- testing(wine_split)

```

```{r load heart_data+split, include=FALSE}
urlfile= "https://raw.githubusercontent.com/ml4econ/problem-sets-2020/master/datasets/heart.csv"
hearts<- read_csv(url(urlfile))
set.seed(167)
hearts_split<- initial_split(hearts, prop=0.7)
hearts_split
heart_train<- training(hearts_split)
heart_test<- testing(hearts_split)
```

# Trees

## Open Q1


```{r}
formula_part <- target ~ sex + cp + chol
formula_full <- target ~ .
```

```{r reducedFtree}
reducedtree<- rpart(formula_part, data = heart_train , method = "class")
fancyRpartPlot(reducedtree, caption = NULL)
```
```{r twomodels_setting}
# first model output
firstModel<- rpart(formula = formula_full, data = heart_train, method = "class", minsplit = 2, minbucket = 1)
printcp(firstModel)
# second model output
secondModel<- rpart(formula = formula_full, data = heart_train, method = "class")
printcp(secondModel)
```

In the first model we used 9 variables and in the second we used 4 variables.

## Predictions

```{r include=FALSE}
# third model output
thirdModel<- rpart(formula = formula_part, data = heart_train, method = "class", minsplit = 2, minbucket = 1)
printcp(firstModel)
# forth model output
forthModel<- rpart(formula = formula_full, data = heart_train, method = "class")
printcp(secondModel)
```

```{r}
# Good formula full, train
predA<- predict(secondModel, heart_train, type = "class")

train_tab <- table(predA, heart_train$target)
train_tab %>% 
  confusionMatrix()

# not good
predB<- predict(secondModel, heart_test, type = "class")

train_tab <- table(predB, heart_test$target)
train_tab %>% 
  confusionMatrix()


# Good formula full, train
predC<- predict(forthModel, heart_train, type = "class")

train_tab <- table(predC, heart_train$target)
train_tab %>%
  confusionMatrix()

# not good
predD<- predict(forthModel, heart_test, type = "class")

train_tab <- table(predD, heart_test$target)
train_tab %>% 
  confusionMatrix()

```

